"""add hole pars and external id to courses

Revision ID: 506a91988527
Revises: b5da697c9690
Create Date: 2026-03-21 17:21:18.820742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506a91988527'
down_revision: Union[str, Sequence[str], None] = 'b5da697c9690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('hole_pars', sa.JSON(), nullable=True))
    op.add_column('courses', sa.Column('external_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'external_id')
    op.drop_column('courses', 'hole_pars')
    # ### end Alembic commands ###
